define([
    'tau/libs/jquery/jquery'
    ,'tau/libs/jquery/jquery.isSupport'
    ,'tau/libs/jquery/jquery.ui'
    ,'tau/libs/jquery/jquery.ui.sortable.performance'
    ,'tau/libs/jquery/jquery.tmpl'
    ,'tau/libs/jquery/jquery.mousewheel'
    ,'tau/libs/jquery/jquery.ui.timepicker'
    ,'tau/libs/jquery/jquery.ui.confirmation'
    ,'tau/libs/jquery/jquery.notifyBar'
    ,'tau/libs/jqote2/jquery.jqote2'
    ,'tau/libs/jquery/jquery.ui.animateWithCss'
    ,'tau/libs/jquery/jquery.ui.sprite'
    ,'tau/libs/jquery/jquery.ui.tauPopup'
    ,'tau/libs/jquery/jquery.ui.tauBubble'
    ,'tau/libs/jquery/jquery.ui.tauConfirm'
    ,'tau/libs/jquery/jquery.ui.position'
    ,'tau/libs/jquery/jquery.textEditor'
    ,'tau/libs/jquery/jquery.ui.tauSortable'
    ,'tau/libs/jquery/jquery.ui.tauSelectable'
    ,'tau/libs/jquery/jquery.ui.tauProgressIndicator'
    ,'tau/libs/jquery/jquery.scrollTo'
    ,'tau/libs/jquery/jquery.gid'
    ,'tau/libs/jquery/jquery.ui.pscroller'
    ,'tau/libs/jquery/jquery.ui.rselect'
    ,'tau/libs/jquery/rhinoslider'
    ,'tau/libs/respond/respond.min'
], function($){
    return $;
});

